os: Visual Studio 2017

version: 1.0.0.{build}

configuration:
- Debug

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
  - ps: Start-FileDownload 'https://download.microsoft.com/download/8/F/9/8F9659B9-E628-4D1A-B6BF-C3004C8C954B/dotnet-1.1.1-sdk-win-x64.exe'
  - cmd: dotnet-1.1.1-sdk-win-x64.exe /quiet
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\
  COVERALLS_REPO_TOKEN:
    secure: Eq/3VV5DVAeQAlQhe6hvy21IYPo5uY4fWKxvC4pxdq3giJzcwFp1QxBvRpXJ8Wkw

before_build:
# restore src and examples
- dotnet restore .\src\ExcelFormulaParser\ExcelFormulaParser.csproj
- dotnet restore .\src\ExcelFormulaExpressionParser\ExcelFormulaExpressionParser.csproj
- nuget  restore .\examples\ExcelFormulaParserSample\ExcelFormulaParserSample.csproj -PackagesDirectory packages

build_script:
# build ExcelFormulaParser
- dotnet build .\src\ExcelFormulaParser\ExcelFormulaParser.csproj -c %CONFIGURATION% --framework net452

# build ExcelFormulaExpressionParser
- dotnet build .\src\ExcelFormulaExpressionParser\ExcelFormulaExpressionParser.csproj -c %CONFIGURATION% --framework net452

# build ExcelFormulaParserSample
# - cmd: msbuild .\examples\ExcelFormulaParserSample\ExcelFormulaParserSample.csproj /p:Configuration=%CONFIGURATION%

# restore and build Tests
- dotnet restore .\tests\ExcelFormulaParser.Tests\ExcelFormulaParser.Tests.csproj
- dotnet build .\tests\ExcelFormulaParser.Tests\ExcelFormulaParser.Tests.csproj -c %CONFIGURATION%
- dotnet restore .\tests\ExcelFormulaExpressionParser.Tests\ExcelFormulaExpressionParser.Tests.csproj
- dotnet build .\tests\ExcelFormulaExpressionParser.Tests\ExcelFormulaExpressionParser.Tests.csproj -c %CONFIGURATION%

test_script:
  - nuget.exe install OpenCover -ExcludeVersion
  - nuget.exe install coveralls.net -ExcludeVersion
  - pip install codecov

  - cmd: '"OpenCover\tools\OpenCover.Console.exe" -register:user -target:dotnet.exe -targetargs:"test tests\ExcelFormulaParser.Tests\ExcelFormulaParser.Tests.csproj --no-build" -returntargetcode -filter:"+[ExcelFormulaParser]* -[ExcelFormulaParser.Tests*]*" -mergeoutput -output:coverage.xml -oldstyle -searchdirs:".\tests\ExcelFormulaParser.Tests\bin\%CONFIGURATION%\net452"'
  - cmd: '"OpenCover\tools\OpenCover.Console.exe" -register:user -target:dotnet.exe -targetargs:"test tests\ExcelFormulaExpresionParser.Tests\ExcelFormulaExpressionParser.Tests.csproj --no-build" -returntargetcode -filter:"+[ExcelFormulaExpressionParser]* -[ExcelFormulaExpressionParser.Tests*]*" -mergeoutput -output:coverage.xml -oldstyle -searchdirs:".\tests\ExcelFormulaExpressionParser.Tests\bin\%CONFIGURATION%\net452"'
  - codecov -f "coverage.xml"
  - coveralls.net\tools\csmacnz.Coveralls.exe --opencover -i .\coverage.xml